# Generated by Django 4.2.2 on 2023-07-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('about', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('authors', models.ManyToManyField(to='hiphop.singer')),
            ],
        ),
        migrations.AddIndex(
            model_name='singer',
            index=models.Index(fields=['slug'], name='hiphop_sing_slug_c7b819_idx'),
        ),
    ]
